# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Implement Updates

on:
  push:
    branches: [ "master" ]
    paths: ['domains/**']
  pull_request:
    branches: [ "master" ]
    paths: ['domains/**']

permissions:
  contents: read

jobs:
  execute:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Execute script
      env:
        PYRK_API_KEY: ${{ secrets.PYRK_API_KEY }}
        PYRK_API_SECRET_KEY: ${{ secrets.PYRK_API_SECRET_KEY }}
        PYRK_RATE: '3'
        PYRK_RETRIES: '2'
        PYTHONPATH: ${{ github.workspace }}
      run: |
        python dns_execute.py >> $EXECUTE_RESULT
    - name: Commit Updates
      if: env.EXECUTE_RESULT == 'COMMIT_REQUIRED'
      run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "update ids"
          git push